{
 "title": "Crash/Restart Metrics & Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User Service Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"user-service\"}"
    }
   ]
  },
  {
   "title": "User Service Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"user-service\"} |= \"api running on 3002\" [5m])) by (container)"
    }
   ]
  },
  {
   "title": "Tweet Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"tweet-service\"}"
    }
   ]
  },
  {
   "title": "Tweet Service Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿(﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿count_over_time﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿(﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿{﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿container﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿=﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿\"tweet-service\"﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿}﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ |= ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿\"api running on ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿3001﻿﻿\" ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿[﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿5m﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿]﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿)﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿)﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ by ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿(﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿container﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿)﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿"
    }
   ]
  },
  {
   "title": "API Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container=\"krakend\"}"
    }
   ]
  }
 ]
}